# Generated by Django 4.0.4 on 2022-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_author_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to='main.author'),
        ),
    ]
