# Generated by Django 4.0.4 on 2022-07-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
