# Generated by Django 4.0.4 on 2022-08-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chooses',
        ),
        migrations.AddField(
            model_name='choose',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
            preserve_default=False,
        ),
    ]
