# Generated by Django 4.0.4 on 2022-08-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_question_chooses_choose_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
