# Generated by Django 4.0.4 on 2022-08-03 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('teacher', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('first_day', models.IntegerField()),
                ('second_day', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
